---
title: "My great analysis"
format: html
date: today
toc: true
---

### Render report
```{r}
#| eval: false
quarto::quarto_render(input = "example.qmd", output_file = paste0("example_", Sys.Date(), ".html"))
```

## Setup

```{r packages}
#| message: false
library(tidyverse)
```

## Data Exploration

```{r}
ggplot(data = mtcars, aes(x = factor(cyl), y = mpg)) +
  theme_bw() +
  geom_violin() +
  geom_point()
```


## Analysis

```{r}
m <- lm(mpg ~ factor(cyl), data = mtcars)
summary(m)
```


## Reproducibility

### Data

Data available for download via CSV/Excel buttons (do not use this as data source, but as confirmation and for posterity)

<details>
  <summary>Show data</summary>
```{r}
DT::datatable(mtcars, extensions = 'Buttons',
              options = list(dom = 'Bfrtip', buttons = c('csv', 'excel')))
```
</details>

### Packages & Session Info

Make sure you [cite](https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/) important packages in your manuscripts

<details>
  <summary>Show packages</summary>

```{r}
#| results: asis
report::report_packages()
report::cite_packages()
```


```{r}
devtools::session_info()
```

</details>


